DEBUG_MODE = True
WORLD_DOWNLOADER = False
BASE_DIR = "./u_worlds"


BLOCK_ENTITY_UPDATES = False
SPAWN_XP = False
VEHICLE_MOVE = False
DECLARE_RECIPES = False
PLAYER_ABILITIES = False
NBT_QUERY_RESP = False
TAB_COMPLETE = False
PLAYER_INFO = False